# Generated by Django 2.0.5 on 2018-05-06 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inputimage_styleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inputimage',
            name='image',
            field=models.FileField(upload_to='static/images/input'),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='image',
            field=models.FileField(upload_to='static/images/style'),
        ),
    ]
