# Generated by Django 2.0.5 on 2018-05-06 21:54

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180506_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputimage',
            name='image',
            field=models.FileField(upload_to=main.models.random_input_image_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='image',
            field=models.FileField(upload_to='static/images/style', validators=[django.core.validators.FileExtensionValidator(['jpg'])]),
        ),
    ]
