# Generated by Django 2.0.5 on 2018-05-07 11:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180506_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(choices=[(0, 'private'), (1, 'unlisted'), (2, 'public')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'working'), (2, 'finished'), (3, 'failed')], default=0)),
                ('log', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_started_at', models.DateTimeField(null=True)),
                ('job_finished_at', models.DateTimeField(null=True)),
                ('num_steps', models.IntegerField(default=300, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(10)])),
                ('style_weight', models.IntegerField(default=1000)),
                ('content_weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='inputimage',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'unlisted'), (2, 'public')], default=0),
        ),
        migrations.AlterField(
            model_name='inputimage',
            name='copyright_notice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inputimage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='copyright_notice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='job',
            name='input_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.InputImage'),
        ),
        migrations.AddField(
            model_name='job',
            name='style_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StyleImage'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
