# Generated by Django 2.0.5 on 2018-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180507_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='uuid',
            field=models.CharField(blank=True, default='Wxq9YU9DkWc85t9qXuuMw7YGrgNqMHBdjWWXkBGVje6ZDiDugb', max_length=50, unique=True),
        ),
    ]
