# Generated by Django 2.0.5 on 2018-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180507_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(blank=True, default='P2ENVQCTASenGMK3YvtbMwZvjk8bJVY6niETGjm8W8vABGiva5', max_length=50, unique=True),
        ),
    ]
