# Generated by Django 2.0.5 on 2018-05-12 14:03

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180507_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='content_weight',
        ),
        migrations.RemoveField(
            model_name='job',
            name='log',
        ),
        migrations.RemoveField(
            model_name='job',
            name='num_steps',
        ),
        migrations.AlterField(
            model_name='inputimage',
            name='image',
            field=models.ImageField(upload_to=main.models.random_input_image_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_image',
            field=models.ImageField(null=True, upload_to=main.models.random_output_image_file_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_weight',
            field=models.FloatField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(blank=True, default='nnagbhXhWYbqtrkiFBESrmXiEaphfU6G7KYBw3LR69Vs8ghBP3', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='image',
            field=models.ImageField(upload_to='static/images/style', validators=[django.core.validators.FileExtensionValidator(['jpg'])]),
        ),
    ]
