# Generated by Django 2.0.5 on 2018-05-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180512_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='styleimage',
            name='description',
        ),
        migrations.AddField(
            model_name='inputimage',
            name='public_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='styleimage',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputimage',
            name='copyright_notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputimage',
            name='visibility',
            field=models.IntegerField(choices=[(2, 'public'), (0, 'private'), (1, 'unlisted')], default=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(blank=True, default='Qs4K8jPULANtGGDQAMrF5DY6DycvSi4nsczPBmpS83vQoEYs4g', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='visibility',
            field=models.IntegerField(choices=[(2, 'public'), (0, 'private'), (1, 'unlisted')], default=2),
        ),
    ]
