# Generated by Django 2.0.5 on 2018-05-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180512_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputimage',
            name='visibility',
            field=models.IntegerField(choices=[(2, 'public'), (1, 'unlisted'), (0, 'private')], default=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(default='d2TQCng9Js2Pf53oixtTRMHintKsGcqQFbD82DZ8jiGZ2dzyJv', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='visibility',
            field=models.IntegerField(choices=[(2, 'public'), (1, 'unlisted'), (0, 'private')], default=2),
        ),
    ]
