# Generated by Django 2.0.5 on 2018-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180512_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
