# Generated by Django 2.0.5 on 2018-05-16 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180516_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleimage',
            name='image',
            field=models.ImageField(upload_to='style', validators=[django.core.validators.FileExtensionValidator(['jpg'])]),
        ),
    ]
